drift/Controllers/CompetitionResultController.cs
using System;
using System.Linq;
using drift.Models.Dto;
using drift.Service;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace drift.Controllers
{
    public class CompetitionResultController : Controller
    {
        private CompetitionResultService _resultService;
        private CompetitionScoreService _scoreService;
        private UserService _userService;

        public CompetitionResultController(CompetitionScoreService scoreService, CompetitionResultService resultService,
            UserService userService)
        {
            _scoreService = scoreService;
            _resultService = resultService;
            _userService = userService;
        }

        [HttpGet]
        public IActionResult GetResults(int competitionId)
        {
            var bracket = _resultService.getResultsBracket(competitionId);
            bracket.CompetitionId = competitionId;
            return View(bracket);
        }


        [HttpPost]
        public IActionResult GetResults(SetResultsRequest request)
        {
            _resultService.storeResult(request);
            return RedirectToAction("GetResults", new {competitionId = request.competitionId});
        }

        [HttpGet]
        public IActionResult GetAllStagesResults(int competitionId)
        {
            var results = _resultService.GetAllStagesResults(competitionId);
            return View(results);
        }

        [HttpPost]
        public IActionResult SetScores(CompetitionScoreSetRequest request)
        {
            _scoreService.SetCompetitionScore(request.Scores, request.competitionId);
            return RedirectToAction("GetScores", new
            {
                competitionId = request.competitionId
            });
        }


        [HttpGet]
        public IActionResult GetScores(int competitionId, string participantName = null)
        {
            var competition = _userService.GetCompetition(competitionId);
            var score = _resultService.GetScore(competitionId);
            if (!string.IsNullOrEmpty(participantName))
            {
	            score = score.Where(x => x.ParticipantName == participantName).ToList();
                if (score.Count == 0)
                {
                    score = _resultService.GetScore(competitionId).Where( x => x.ParticipantNumber.ToString() == participantName).ToList();
                }
            }
            return View(new CompetitionScoreResponse()
                {Scores = score, competitionId = competition.Id, createdById = competition.CreatedById});
        }

        [HttpGet]
        public IActionResult StartMainPhase(int competitionId, bool autoGenerate)
        {
            _resultService.GenerateResults(competitionId, HttpContext.User.Identity.Name, autoGenerate);
            return RedirectToAction("GetResults", new {competitionId = competitionId});
        }
    }
}

drift/Views/CompetitionResult/GetAllStagesResults.cshtml
@model drift.Models.Dto.AllStagesResultResponse

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
    var i = 1;
}

<h1 class="text-center">Результаты соревнований</h1>
<table class="table">
    <thead>
    <th scope="col">Название</th>
    <th scope="col">Дата</th>
    </thead>
    <tbody>
    @foreach (var result in @Model.CompetitionDtos)
    {
        <tr>
            <td>@result.Name</td>
            <td>@result.StartDate</td>
        </tr>
    }
    </tbody>
</table>
<h1 class="text-center">Результаты</h1>
<table class="table">
    <thead>
    <tr>
        <th scope="col">Место</th>
        <th scope="col">Имя</th>
        @foreach (var stage in @Model.CompetitionDtos)
        {
            <th scope="col">Очки за соревнование @stage.Name</th>
        }

        <th scope="col">Очки</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var result in @Model.Results)
    {
        <tr>
            <th scope="row">@i</th>
            <td>@result.ParticipantName</td>
            @foreach (var stage in @Model.CompetitionDtos)
            {
                <td scope="col">@(result.competitionScores[stage.Id] == 0 ? "-" : result.competitionScores[stage.Id].ToString())</td>
            }
            <td>@result.TotalScore</td>
            @{ i++; }

        </tr>
    }
    </tbody>
</table>

drift/Views/CompetitionResult/GetResults.cshtml
@model drift.Models.Dto.CompetitionBracket

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}
@{
}

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="https://www.aropupu.fi/bracket/jquery-bracket/dist/jquery.bracket.min.js"></script>

<script type="text/javascript">

function SelectWinners()
{
    let topEightIds = ['#1-1','#5-1','#9-1','#13-1','#17-1','#21-1','#25-1','#29-1'];
    let topFourIds = ['#3-2','#11-2','#19-2','#27-2','#35-1'];
    let topTwoIds = ['#7-3','#23-3'];
    let winnerId = ['#15-4'];
    topEightIds.forEach((topEight)=>{
        let i = parseInt(topEight.substr(topEight.indexOf('#')+1,topEight.indexOf('-')-1));
        let firstParticpantNumber =parseInt( $(`#${i-1}-0`).html());
        let secondParticpantNumber = parseInt($(`#${i+1}-0`).html());
        let  res = Math.min(firstParticpantNumber,secondParticpantNumber);
        $(`${topEight}`).html(res);
    });
    topFourIds.forEach((topFour)=>{
             let i = parseInt(topFour.substr(topFour.indexOf('#')+1,topFour.indexOf('-')-1));
             let firstParticpantNumber =parseInt( $(`#${i-2}-1`).html());
             let secondParticpantNumber = parseInt($(`#${i+2}-1`).html());
             let  res = Math.min(firstParticpantNumber,secondParticpantNumber);
             $(`${topFour}`).html(res);
    });
    topTwoIds.forEach((topTwo)=>{
             let i = parseInt(topTwo.substr(topTwo.indexOf('#')+1,topTwo.indexOf('-')-1));
             let firstParticpantNumber =parseInt( $(`#${i-4}-2`).html());
             let secondParticpantNumber = parseInt($(`#${i+4}-2`).html());
             let  res = Math.min(firstParticpantNumber,secondParticpantNumber);
             $(`${topTwo}`).html(res);
        });
     let firstParticpantNumber =parseInt( $(`#7-3`).html());
     let secondParticpantNumber = parseInt($(`#23-3`).html());
     let  res = Math.min(firstParticpantNumber,secondParticpantNumber);
     $(`${winnerId}`).html(res);
    
}

function getRandomArbitrary(min, max) {
  return Math.random() * (max - min) + min;
}

function saveFn(newData) {
      console.log(newData);
      console.log(newData);

      if (newData.results[0][3][1][0]!=null && newData.results[0][3][1][1]!=null
      &&newData.results[0][3][0][0]!= null && newData.results[0][3][0][1]!=null){
                $('#set-results').prop('disabled',false);
             $('#bracket-input').prop('value',JSON.stringify(newData.results[0]));
        }
       


}
 

  var model = '@Html.Raw(Json.Serialize(Model))';
  var bigData = JSON.parse(model);
  var data= bigData.firstStageResults;
  var dataSecondStage = bigData.secondStageResults;
  var dataThirdStage = bigData.thirdStageResults;
  var dataFourthStage = bigData.fourthStageResults;
let minimalData = {
     teams: [
       [data[0].participantName, data[1].participantName],
       [data[2].participantName, data[3].participantName],
       [data[4].participantName, data[5].participantName],
       [data[6].participantName, data[7].participantName],
       [data[8].participantName, data[9].participantName],
       [data[10].participantName, data[11].participantName],
       [data[12].participantName, data[13].participantName],
       [data[14].participantName, data[15].participantName]
     ],
     results: [
         [
           [[data[0].firstPhaseScore, data[1].firstPhaseScore], [data[2].firstPhaseScore, data[3].firstPhaseScore],[data[4].firstPhaseScore, data[5].firstPhaseScore], [data[6].firstPhaseScore, data[7].firstPhaseScore],[data[8].firstPhaseScore, data[9].firstPhaseScore],[data[10].firstPhaseScore, data[11].firstPhaseScore],[data[12].firstPhaseScore, data[13].firstPhaseScore], [data[14].firstPhaseScore, data[15].firstPhaseScore]],
           [[dataSecondStage[0].secondPhaseScore, dataSecondStage[1].secondPhaseScore], [dataSecondStage[2].secondPhaseScore, dataSecondStage[3].secondPhaseScore],[dataSecondStage[4].secondPhaseScore, dataSecondStage[5].secondPhaseScore],[dataSecondStage[6].secondPhaseScore, dataSecondStage[7].secondPhaseScore]],
           [[dataThirdStage[0].thirdPhaseScore, dataThirdStage[1].thirdPhaseScore], [dataThirdStage[2].thirdPhaseScore, dataThirdStage[3].thirdPhaseScore]],
            [[dataFourthStage[0].fourthPhaseScore, dataFourthStage[1].fourthPhaseScore],[dataFourthStage[2].fourthPhaseScore, dataFourthStage[3].fourthPhaseScore]]
         ]
     ]
  }


 
      
   $(document).ready(function ($) {
      $('.something').bracket({
             init: minimalData,
             save: saveFn
            });
   });

</script>
<h1 class="text-center">Результаты совревнования</h1>
<div class="something"></div>
<table class="table">
    <thead>
    <tr>
        <th scope="col">Место</th>
        <th scope="col">Номер машины</th>
        <th scope="col">Имя</th>
        <th scope="col">Машина</th>
        <th scope="col">Очки</th>
    </tr>
    </thead>
    <tbody>
    @if (@Model.ResultsSet)
    {
        @foreach (var result in @Model.OverallResults)
        {
            <tr>
                <th scope="row">@result.Place</th>
                <td>@result.CarNumber</td>
                <td>@result.User.UserName</td>
                <td>@result.ParticipantName</td>
                <td>@result.TotalScore</td>
            </tr>
        }
    }
    else
    {
        <form method="post">
            <input type="hidden" name="bracket" id="bracket-input">
            <input type="hidden" name="competitionId" id="comp-id" value="@Model.CompetitionId">

            <button class="btn btn-success" id="set-results" type="submit" disabled>
                Установить результаты
            </button>
        </form>
    }

    </tbody>
</table>

drift/Views/CompetitionResult/GetScores.cshtml
@using Microsoft.AspNetCore.Http
@model drift.Models.Dto.CompetitionScoreResponse
@inject IHttpContextAccessor httpContextAccessor

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
    var autoGen = false;
}

<form method="GET" asp-controller="CompetitionResult"
      asp-action="GetScores" 
      asp-route-competitionId="@Model.competitionId" 
      asp-route-participantName="@Model.participantName"
      >
	<div>
		<input type="text" asp-for="participantName" />
		<input type="hidden" value="@Model.competitionId" asp-for="competitionId" />
	</div>
    <button class="btn btn-success" type="submit">
			Найти
		</button>
</form>



<table class="table">
    <thead>
    <tr class="bg-primary">
        <th scope="col">Участник</th>
        <th scope="col">Номер участника</th>
        <th scope="col">Очки за угол</th>
        <th scope="col">Очки за трассу</th>
        <th scope="col">Очки за стиль</th>
        <th scope="col">Попытка</th>
        <th scope="col">Общие очки</th>
    </tr>
    </thead>
    <tbody>
    @for (var i = 0; i < Model.Scores.Count; i++)
    {
        <tr class="bg-info">
            @if (i == 0 || @Model.Scores[i].ParticipantName != @Model.Scores[i - 1].ParticipantName)
            {
                <th scope="col">@Model.Scores[i].ParticipantName</th>
                <th scope="col">@Model.Scores[i].ParticipantNumber</th>
            }
            else
            {
                <th></th>
                <th></th>
            }
            <th scope="col">@Model.Scores[i].AngleScore</th>
            <th scope="col">@Model.Scores[i].TrackScore</th>
            <th scope="col">@Model.Scores[i].StyleScore</th>
            <th scope="col">@Model.Scores[i].Attempt</th>
            <th scope="col">@Model.Scores[i].Total</th>
        </tr>
        @if (i == @Model.Scores.Count - 1 || @Model.Scores[i].ParticipantName != @Model.Scores[i + 1].ParticipantName)
        {
            <tr class="bg-success">
                <th scope="col">Лучшие результаты</th>
                <th scope="col"></th>
                <th scope="col">@Model.Scores[i].BestAngle</th>
                <th scope="col">@Model.Scores[i].BestTrack</th>
                <th scope="col">@Model.Scores[i].BestStyle</th>
                <th scope="col"></th>
                <th scope="col">@Model.Scores[i].BestTotal</th>
            </tr>
        }
    }
    </tbody>
</table> 
@if (Model.createdById == httpContextAccessor.HttpContext.User.Identity.Name)
{
    <a class="nav-link text-dark" asp-controller="CompetitionResult" asp-action="StartMainPhase" asp-route-autoGenerate="true" asp-route-competitionId="@Model.competitionId">
        <button class="btn btn-success" type="submit">
            Начать основной этап (автоматическая генерация)
        </button>
    </a>
    
    <a class="nav-link text-dark" asp-controller="CompetitionResult" asp-action="StartMainPhase" asp-route-autoGenerate="false" asp-route-competitionId="@Model.competitionId">
        <button class="btn btn-success" type="submit">
            Начать основной этап (ручная генерация)
        </button>
    </a>
}